apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-k8smonitor-service
  labels:
    app: k8smonitor
spec:
  type: {{ .Values.service.type }}
  selector:
    app: k8smonitor
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
